<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>scrapetest</AssemblyName>
    <EmbySystemDir Condition="'$(EmbySystemDir)' == ''">C:\Users\user\programs\embyserver\system</EmbySystemDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Emby.Plugin.MusicMetaEnhanced\Emby.Plugin.MusicMetaEnhanced.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MediaBrowser.Common">
      <HintPath>$(EmbySystemDir)\MediaBrowser.Common.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MediaBrowser.Controller">
      <HintPath>$(EmbySystemDir)\MediaBrowser.Controller.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="MediaBrowser.Model">
      <HintPath>$(EmbySystemDir)\MediaBrowser.Model.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
